apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: snort
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snort
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
